### ISSUE TITLE
The opam-publish prepare does not use the opam file in the archive.

### ISSUE THREAD

**Issue by mvalle** [ocaml/opam-publish#39] opened 2016-04-24 12:19 UTC
When I run `opam-publish prepare` against an archive, the the generated `opam` file is not the same as the `opam` file inside the archive.

As a concrete example:

```
$ opam-publish prepare https://github.com/mvalle/ocaml-ofx/archive/ofx.0.1.5.zip
$ wget https://github.com/mvalle/ocaml-ofx/archive/ofx.0.1.5.zip
$ unzip ofx.0.1.5.zip
$ diff ofx.0.1.5/opam ocaml-ofx-ofx.0.1.5/opam 
3a4,5
> name: "ofx"
> version: "0.1.5"
8c10,12
< build: [make]

---
> build: [
>   [make]
> ]
15a20
> available: [ocaml-version >= "4.02.0" ]
\ No newline at end of file
$ 
```

Of the three differences:
1. Removing the `name` and `version` options.
2. Tidying up the `build` option.
3. Removing the `available` option.

Number 1 and 2 are fine. But number 3 is an annoyance, as you'll have to add the `available` option back in.

**Comment by AltGr** [comment] 2016-06-15 13:17
Thanks for reporting. Indeed, files in the repository shouldn't mention the package name or version (which are inferred from file name), so opam-publish removes that; in doing so, it parses and re-prints the file, which causes the format change in the `build:` field -- opam 2.0 has a feature to re-print while keeping the format of unchanged fields, but it's not there yet.

3. clearly seems to be a bug though, there is no reason the field should be removed; may that be due to the missing newline ? I'll check.

**Comment by jordwalke** [comment] 2017-05-11 22:44
@bordoley also found that in his `opam publish prepare` step, dependencies were being removed if they were marked "build". I wonder if that's another bug?

**Comment by bordoley** [comment] 2017-05-11 22:51
In the Immutable-re repo I have the following opam file:
```
opam-version: "1.2"
name: "immutable"
version: "0.0.11"
license: "BSD-3-Clause"
dev-repo: "https://facebookincubator.github.io/immutable-re/"
bugs-reports: "https://github.com/facebookincubator/immutable-re/issues"
maintainer: "Dave Bordoley <bordoley@gmail.com>"
authors: [
  "Dave Bordoley <bordoley@gmail.com>"
]
tags: [ "reason" "reasonml" "ocaml" "immutable" ]
depends: [
  "reason" { build >=  "1.13.3" }
]
build: [
  [ make "build" ]
]
available: [ ocaml-version >= "4.02" & ocaml-version < "4.05" ]
```

When preparing a release I execute:

```
bordoleymbp6127:immutable-re2 bordoley$ opam-publish prepare https://github.com/facebookincubator/immutable-re/archive/0.0.11.tar.gz
[0.0.11.tar.gz] https://github.com/facebookincubator/immutable-re/archive/0.0.11.tar.gz downloaded
Enter passphrase for key '/Users/bordoley/.ssh/id_rsa': 
Enter passphrase for key '/Users/bordoley/.ssh/id_rsa': 
Template metadata generated in immutable.0.0.11/.
  * Check the 'opam' file
  * Fill in or check the description of your package in 'descr'
  * Check that there are no unneeded files under 'files/'
  * Run 'opam publish submit ./immutable.0.0.11' to submit your package
```

but the result opam file in the release doesn't appear to be generated correctly:
```
bordoleymbp6127:immutable-re2 bordoley$ cd immutable.0.0.11/
bordoleymbp6127:immutable.0.0.11 bordoley$ cat opam 
opam-version: "1.2"
maintainer: "Dave Bordoley <bordoley@gmail.com>"
authors: "Dave Bordoley <bordoley@gmail.com>"
license: "BSD-3-Clause"
tags: ["reason" "reasonml" "ocaml" "immutable"]
dev-repo: "http://facebookincubator.github.io/immutable-re/"
build: [make "build"]
available: [ocaml-version >= "4.02" & ocaml-version < "4.05"]
bordoleymbp6127:immutable.0.0.11 bordoley$ 
```

**Comment by jordwalke** [comment] 2017-05-11 22:52
Relatedly, I'm wondering if things can be simplified by just having opam publish prepare use the opam file inside of the tarball. Why does there need to be two? I'm sure there's a reason, but this was confusing for someone going through the flow for the first time.

**Comment by AltGr** [comment] 2017-05-12 08:29
There are two aspects:
- The idea is that you test your package locally using `opam pin`, as advised [here](http://opam.ocaml.org/doc/Packaging.html). To that end, opam-publish preferably uses the opam file _that the package is pinned with_, so that you can `opam pin edit` and loop, rather than having to generate a new archive when you edit. Mentionning this as it could be the cause of the first error.
- The latter error is clearly missing error messages, but I believe more recent versions of opam-publish should be better behaved (they will be in any case, once moved to the opam 2.0 libs).  Typo in `bug-reports:` and syntax error in `build:` caused the fields to be silently ignored. Pinning the package would probably have given more details.

**Comment by jordwalke** [comment] 2017-05-12 09:02
> "To that end, opam-publish preferably uses the opam file that the package is pinned with"

So it is assumed that you had first ran `opam pin` on your package before running publish? If not, I'm confused about why you've mention pinning at all. We test by using pinning of our local package. But publishing is an entirely different story and we do that on a clean branch. I would assume that if opam publish expects us to be operating within a pinned package it would have mentioned this much.

**Comment by dbuenzli** [comment] 2017-05-12 09:05
TBH I found `opam publish prepare` a bit too mysterious and confusing in its operating mode this is why `topkg opam pkg` generates the package by itself (using the opam file in the repo), and `topkg opam submit` simply uses `opam-publish submit`.

Regarding `opam pin edit` I personally never use this and I suspect many don't either: it becomes cumbersome to extract your changes and bring them back into your repo. It's easier to change them in the repo and update your pin.

**Comment by jordwalke** [comment] 2017-05-12 09:06
> Regarding opam pin edit I personally never use this and I suspect many don't either:

I just learned it existed three minutes ago.

**Comment by jordwalke** [comment] 2017-05-12 09:10
So is the idea behind first pinning your package, that it removes the need for something like a `make publish` command, which prepares the repo for publishing, because the pinned form is likely similar to the published form?

**Comment by rjbou** [comment] 2020-04-28 13:11
Seems it is no more an issue on current version. Thanks!

**Closed by rjbou** 2020-04-28 13:11 UTC
